# Timeouts (seconds)
BRREG_TIMEOUT = 10
NAV_TIMEOUT = 15
PAGE_GOTO_TIMEOUT = 20
PAGE_NAV_TIMEOUT = 30
OPENROUTER_TIMEOUT = 45

# Concurrency limits
NAV_MAX_CONCURRENT = 20
PLAYWRIGHT_MAX_CONTEXTS = 5
OPENROUTER_MAX_CONCURRENT = 10

# Budgets
SCRAPE_BUDGET_PER_ORG = 10

# Wall-clock limits (minutes)
WALL_CLOCK_CUTOFF_MINUTES = 42
